name: Go

on:
  push:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6
          golangci-lint run -v ./...

  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: |
          go install github.com/boumenot/gocover-cobertura@latest
          go install github.com/vladopajic/go-test-coverage/v2@latest
      - name: Test with the Go CLI
        run: |
          GOMAXPROCS=$(nproc) go test -coverprofile=coverage.out -cover -race -tags="unit" -p $(nproc) -parallel=$(nproc) ./...
          go-test-coverage --config=./.testcoverage.yml
          gocover-cobertura < coverage.out > coverage.xml
      - name: Bench
        run: go test -bench=. -run="^$$" ./...
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          path: coverage.xml